### ISSUE TITLE
current validation rules only for BT-131(d) and BT-132(d) allow inconsistencies in BT-131(t)/BT-132(t)

### ISSUE THREAD

**Issue by gabrieledall** [OP-TED/eForms-SDK#783]
The validation rules that make sure,any opening of tenders in open procedurese will take place after the end of the submission deadline is reached are currently inmplemented in a way that is not fully consitent:

Currently (at least from SDK 1.72 to 1.10.0) BT-132(d) ist validated according to BT-131(d) as follows:

"condition" : "{ND-PublicOpening} ${(BT-132(d)-Lot is present) and (BT-131(d)-Lot is present)}",
"value" : "{ND-PublicOpening} ${BT-132(d)-Lot >= BT-131(d)-Lot}",

iIt is allowed to have open procedures to be opended on the same day, the submission deadline is reached - this is fine and please do not change this rule, but then:

Opening time and submission time are set separately in BT-131(t) and BT-132(t) and no validation check is implemented to the time-related fields. this makes it ist possible to hand in CNs like this:

BT-131(d) = 11.12.2023 UTC+1:00
BT- 132(d) = 11.12.2023 UTC +1:00

BT-131(t) = 18:00 UTC +1:00
BT-132(t) = 12:00 UTC +1:00

Which would make the opening date/time earlier than the submission deadline date/time.

Could you please correct this issue with a next patch-release of at least SDK-1.10?

Thank you in advance
G.D.

**Comment by YvesJo** [comment]
Hi,
This control is restricted by the current EFX language and shall get fixed with EFX 2.

**Comment by Colan71** [comment]
Hi,
The rule for BT-132(d) in comparison with BT-131(d) is unclear.
We can see in the fields.json for the conditions regarding BT-132(d)-Lot that the error message for rule|text|BR-BT-00132-0151 is 'Opening date' (BT-132) must be later than 'Deadline for receipt of tenders' (BT-131). Still we can validate a notice successfully even though BT-131(d) and BT-132(d) have the exact same date and time. Should this be the case? If so, will you then remove the rule for BT-132(d)-Lot in an upcoming SDK?

**Comment by YvesJo** [comment]
This will be the case until EFX2 will be available

**Comment by Colan71** [comment]
Just to get this crystal clear :) Does this mean that when EFX2 is available there will also be a time validation for BT-131(d) and BT-132(d). So they can still have the same date, but the time for BT-132(d) must be later than the time in BT-131(d)?

**Comment by YvesJo** [comment]
Yes, it will be possible to compare date-time values from the date and time ones.

**Comment by Colan71** [comment]
And the timeline for EFX2 is pre-releases during 2024 as you progress and a final release Q1 2025, right?

**Comment by Colan71** [comment]
Hi,
Can you please inform us when the time validation will be in place?

**Comment by pdonohoe** [comment]
The time validation is also dependent on EFX2, so it would not be fully implemented until Q1 2025.
